<?php

/**
 * Implements hook_cron().
 */
function firebird_module_cron() {
  $exchange_service = \Drupal::service('firebird_module.currency_exchange');
  $exchange_values = $exchange_service->getCurrenciesFromAPI();

  if (!empty($exchange_values) && is_array($exchange_values)) {
    $values = [
      'date' => date("Y-m-d", time()),
      'EUR' => $exchange_values['EUR'],
      'RUB' => $exchange_values['RUB'],
    ];

    try {
      \Drupal::database()->insert('currency_exchange')
        ->fields($values)
        ->execute();
    }
    catch (\Exception $e) {
      \Drupal::logger('currency_exchange_service')->error($e->getMessage());
    }
  }
}

/**
 * Implements hook_theme().
 */
function firebird_module_theme($existing, $type, $theme, $path) {
  return [
    'currency_conversion_form' => [
      'render element' => 'form',
      'template' => 'currency-conversion-form',
    ],
  ];
}
